name: NuGet

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Update version number
      id: version
      run: echo ::set-output name=version::1.0.$(date +%s)

    - name: Build and pack NuGet package
      run: dotnet pack -c Release /p:PackageVersion=${{ steps.version.outputs.version }} ReverieCore.csproj

    - name: Publish NuGet package
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
      run: nuget push **/*.nupkg -s https://api.nuget.org/v3/index.json